# Generated by Django 3.2.12 on 2022-12-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_in_months', models.IntegerField()),
                ('type', models.CharField(choices=[('1', "manufacturer's warranty"), ('2', 'extended warranty')], max_length=1)),
                ('coverage_details', models.TextField()),
                ('exclusions', models.TextField()),
                ('cusomer_service_phone_number', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('qunatity', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.warranty')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shipping_address', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('1', 'card'), ('2', 'cash')], max_length=1)),
                ('order_total', models.IntegerField()),
                ('products', models.ManyToManyField(to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
